env: test
host: test.jobshout.co.uk
logLevel: info

ai:
  enabled: true
  ollamaBaseURL: "https://ollama.workstation.co.uk"
  ollamaModel: "llama3:latest"
  imageBaseURL: "https://images.workstation.co.uk"
  imageModel: "z-image-turbo"
  blogCoverImages: false

api:
  replicas: 1

web:
  replicas: 1
  publicApiURL: "https://test.jobshout.co.uk/api"
  publicWsURL: "wss://test.jobshout.co.uk/api"

pythonRuntime:
  replicas: 1

storage:
  postgres: 10Gi
