env: test
host: test-jobshout.workstation.co.uk
logLevel: info

ai:
  enabled: true
  ollamaBaseURL: "https://ollama.workstation.co.uk"
  ollamaModel: "llama3:latest"

api:
  replicas: 1

web:
  replicas: 1
  publicApiURL: "https://test-jobshout.workstation.co.uk/api"
  publicWsURL: "wss://test-jobshout.workstation.co.uk/api"

pythonRuntime:
  replicas: 1

storage:
  postgres: 10Gi
