import Image from "next/image";
import { cn } from "@/lib/utils/cn";

// The Shout wheel. Generated by docs/brand/tools/build-brand.py; edit the
// geometry there, not the SVG in public/brand. Under 32 px the full wheel
// turns to mush, so it switches to the four-spoke version.
export function BrandMark({ size = 28, className }: { size?: number; className?: string }) {
  return (
    <Image
      src={size < 32 ? "/brand/logo-glyph-small.svg" : "/brand/logo-glyph.svg"}
      alt=""
      aria-hidden
      width={size}
      height={size}
      unoptimized
      className={cn("shrink-0 select-none", className)}
    />
  );
}

// Wheel + wordmark. "Shout" carries the brand gradient.
export function BrandLockup({ className }: { className?: string }) {
  return (
    <span className={cn("inline-flex items-center gap-2.5", className)}>
      <BrandMark size={36} />
      <span className="font-display text-xl font-bold leading-none tracking-[-0.02em] text-foreground">
        Job
        <span className="bg-gradient-to-r from-[#E0218A] via-[#FF3D6E] to-[#FF9A3C] bg-clip-text text-transparent">
          Shout
        </span>
      </span>
    </span>
  );
}
