import Image from "next/image";
import Link from "next/link";

export function Logo({ className }: { className?: string }) {
  return (
    <Link
      href="/"
      aria-label="JobShout.com home"
      className={`group inline-flex items-center gap-2.5 ${className ?? ""}`}
    >
      {/* The Shout wheel, generated by docs/brand/tools/build-brand.py. */}
      <Image
        src="/brand/logo-glyph.svg"
        alt=""
        aria-hidden
        width={36}
        height={36}
        unoptimized
        priority
        className="h-9 w-9 transition-transform duration-200 group-hover:scale-105"
      />
      <span className="font-display text-[1.3rem] font-semibold leading-none tracking-[-0.03em] text-ink">
        JobShout
        <span className="text-mute transition-colors duration-200 group-hover:text-shout">
          .com
        </span>
      </span>
    </Link>
  );
}
