apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobshout-api
  namespace: jobshout
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 1Gi
