apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jobshout

resources:
  - ../../base

patchesStrategicMerge:
  - api-patch.yaml
  - python-runtime-patch.yaml

images:
  - name: jobshout/server
    newTag: production
  - name: jobshout/python-sidecar
    newTag: production
  - name: jobshout/web
    newTag: production
