-- Migration 023: generated images.
--
-- Two changes:
--   1. blog_articles gains a cover image — its URL, the prompt that produced it,
--      and the settings that produced it. The settings are stored rather than
--      inferred because a seed is the only way to reproduce a picture that came
--      out well, and an image whose seed was thrown away can be regenerated but
--      never reproduced.
--   2. generated_images records every image the platform has drawn, whatever
--      asked for it — an article run, an agent calling the generate_image tool,
--      or a person in the UI. One table rather than three because the questions
--      worth asking of it ("what has this org generated", "what did that cost",
--      "who asked for this") do not care which of the three routes was used.
--
-- IDEMPOTENCY IS MANDATORY. database/migrate.go replays every *.up.sql on every
-- boot — there is no schema_migrations table — so a statement that cannot run
-- twice takes down every environment on restart, not just this feature.

ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS cover_image_url    TEXT;
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS cover_image_prompt TEXT;
-- The provider, model, seed and dimensions behind the cover, as JSON rather
-- than five columns: it is written and read whole, never queried by part, and a
-- provider that grows a new setting should not need a migration.
ALTER TABLE blog_articles ADD COLUMN IF NOT EXISTS cover_image_meta   JSONB NOT NULL DEFAULT '{}';

CREATE TABLE IF NOT EXISTS generated_images (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id       UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    -- Nullable: an image generated by a schedule or by an agent acting on its
    -- own has no person behind it, and inventing one would be a lie in the
    -- audit trail. ON DELETE SET NULL so removing a user does not delete the
    -- images their work produced.
    created_by   UUID REFERENCES users(id) ON DELETE SET NULL,
    prompt       TEXT NOT NULL,
    provider     TEXT NOT NULL,
    model        TEXT NOT NULL,
    -- BIGINT because a seed is a 32-bit unsigned value on some providers and
    -- absent on others; -1 records "the provider chose and did not say".
    seed         BIGINT NOT NULL DEFAULT -1,
    width        INTEGER NOT NULL,
    height       INTEGER NOT NULL,
    -- Where the bytes live. Nullable because an image can be generated and
    -- handed straight back without object storage configured, and a row that
    -- records the request is still worth keeping.
    url          TEXT,
    -- What asked for it: 'blog_cover', 'blog_inline', 'agent_tool', 'manual'.
    -- Text rather than an enum so a new caller does not need a migration.
    source       TEXT NOT NULL DEFAULT 'manual',
    duration_ms  INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- The listing this table exists to serve: an org's images, newest first.
CREATE INDEX IF NOT EXISTS idx_generated_images_org_created
    ON generated_images(org_id, created_at DESC);
