package career

// BuiltinPortal is one CareerOps-tracked ATS board (MIT, santifer/career-ops portals.example.yml).
type BuiltinPortal struct {
	Board   string
	Slug    string
	Company string
}

// BuiltinPortals is the scannable Greenhouse / Ashby / Lever subset of the
// CareerOps company list. Companies without a public ATS API are omitted.
func BuiltinPortals() []BuiltinPortal {
	out := make([]BuiltinPortal, len(builtinPortals))
	copy(out, builtinPortals)
	return out
}

var builtinPortals = []BuiltinPortal{
	{"greenhouse", "anthropic", "Anthropic"},
	{"greenhouse", "polyai", "PolyAI"},
	{"greenhouse", "parloa", "Parloa"},
	{"greenhouse", "intercom", "Intercom"},
	{"greenhouse", "humeai", "Hume AI"},
	{"ashby", "elevenlabs", "ElevenLabs"},
	{"ashby", "deepgram", "Deepgram"},
	{"ashby", "vapi", "Vapi"},
	{"ashby", "bland", "Bland AI"},
	{"greenhouse", "airtable", "Airtable"},
	{"greenhouse", "vercel", "Vercel"},
	{"greenhouse", "temporal", "Temporal"},
	{"greenhouse", "arizeai", "Arize AI"},
	{"greenhouse", "runpod", "RunPod"},
	{"greenhouse", "coreweave", "Weights & Biases (CoreWeave)"},
	{"greenhouse", "gleanwork", "Glean"},
	{"greenhouse", "ada", "Ada"},
	{"ashby", "sierra", "Sierra"},
	{"ashby", "decagon", "Decagon"},
	{"ashby", "lindy", "Lindy"},
	{"greenhouse", "speechmatics", "Speechmatics"},
	{"ashby", "n8n", "n8n"},
	{"ashby", "zapier", "Zapier"},
	{"greenhouse", "boomilp", "Boomi"},
	{"ashby", "cohere", "Cohere"},
	{"ashby", "langchain", "LangChain"},
	{"ashby", "pinecone", "Pinecone"},
	{"lever", "mistral", "Mistral AI"},
	{"lever", "palantir", "Palantir"},
	{"greenhouse", "later", "Later"},
	{"greenhouse", "safariai", "Safari AI"},
	{"greenhouse", "hootsuite", "Hootsuite"},
	{"ashby", "klue", "Klue"},
	{"ashby", "glacis-ai", "Glacis AI"},
	{"lever", "sanctuary", "Sanctuary AI"},
	{"ashby", "attio", "Attio"},
	{"ashby", "tinybird", "Tinybird"},
	{"lever", "clarity-ai", "Clarity AI"},
	{"ashby", "perk", "Travelperk"},
	{"ashby", "AlephAlpha", "Aleph Alpha"},
	{"ashby", "DeepL", "DeepL"},
	{"greenhouse", "blackforestlabs", "Black Forest Labs"},
	{"greenhouse", "helsing", "Helsing"},
	{"greenhouse", "celonis", "Celonis"},
	{"greenhouse", "contentful", "Contentful"},
	{"greenhouse", "getyourguide", "GetYourGuide"},
	{"greenhouse", "hellofresh", "HelloFresh"},
	{"greenhouse", "n26", "N26"},
	{"greenhouse", "traderepublicbank", "Trade Republic"},
	{"greenhouse", "sumup", "SumUp"},
	{"lever", "qonto", "Qonto"},
	{"ashby", "forto", "Forto"},
	{"ashby", "lakera.ai", "Lakera"},
	{"greenhouse", "scandit", "Scandit"},
	{"ashby", "cradlebio", "Cradle"},
	{"ashby", "photoroom", "Photoroom"},
	{"lever", "pigment", "Pigment"},
	{"greenhouse", "wayve", "Wayve"},
	{"greenhouse", "isomorphiclabs", "Isomorphic Labs"},
	{"greenhouse", "physicsx", "PhysicsX"},
	{"greenhouse", "stabilityai", "Stability AI"},
	{"ashby", "synthesia", "Synthesia"},
	{"ashby", "faculty", "Faculty"},
	{"ashby", "causaly", "Causaly"},
	{"ashby", "lovable", "Lovable"},
	{"ashby", "legora", "Legora"},
	{"lever", "spotify", "Spotify"},
	{"ashby", "bolt", "Bolt"},
	{"ashby", "mollie", "Mollie"},
	{"lever", "contentsquare", "Hotjar"},
	{"ashby", "corti", "Corti"},
	{"ashby", "pleo", "Pleo"},
	{"greenhouse", "templafy", "Templafy"},
	{"greenhouse", "amplemarket", "Amplemarket"},
	{"ashby", "perplexity", "Perplexity"},
	{"ashby", "claylabs", "Clay Labs"},
	{"greenhouse", "runwayml", "Runway"},
	{"greenhouse", "hightouch", "Hightouch"},
	{"ashby", "workos", "WorkOS"},
	{"ashby", "supabase", "Supabase"},
	{"ashby", "resend", "Resend"},
	{"ashby", "clerk", "Clerk"},
	{"ashby", "inngest", "Inngest"},
	{"greenhouse", "planetscale", "PlanetScale"},
	{"lever", "getir", "Getir"},
	{"greenhouse", "moniepoint", "Moniepoint"},
	{"greenhouse", "jumia", "Jumia"},
	{"ashby", "andela", "Andela"},
}
