apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobshout-com-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jobshout-com-api
  template:
    metadata:
      labels:
        app: jobshout-com-api
    spec:
      containers:
        - name: api
          image: {{ .Values.image.api }}
          ports:
            - containerPort: {{ .Values.service.apiPort }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
            - name: PORT
              value: {{ .Values.service.apiPort | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: jobshout-com-api
spec:
  selector:
    app: jobshout-com-api
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobshout-com-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jobshout-com-web
  template:
    metadata:
      labels:
        app: jobshout-com-web
    spec:
      containers:
        - name: web
          image: {{ .Values.image.web }}
          ports:
            - containerPort: {{ .Values.service.webPort }}
          env:
            - name: JOBSHOUT_COM_API_URL
              value: {{ .Values.env.JOBSHOUT_COM_API_URL | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: jobshout-com-web
spec:
  selector:
    app: jobshout-com-web
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: {{ .Values.service.webPort }}
