{{- if .Values.image.pullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecret }}
  labels:
    {{- include "jobshout-com.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .Values.image.registry (printf "%s:%s" .Values.secrets.registryUsername .Values.secrets.registryPassword | b64enc) | b64enc }}
{{- end }}
